{% set name = "ldas-tools-ldasgen-swig" %}
{% set version = "2.6.7" %}
{% set sha256 = "8a438b53d8fb9cfdb7f57ac3cc132e9a51a723d11d7feaa4550350bde30d947f" %}
{% set ldas_tools_cmake_version = "1.0.7" %}
{% set ldas_tools_al_version = "2.6.6" %}
{% set ldas_tools_ldasgen_version = "2.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [not win]
    - make  # [not win]
    - swig
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

outputs:
  - name: ldas-tools-ldasgen-swig
    script: install-interface.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
        - swig
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
      run:
        - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
    test:
      commands:
        - test -f ${PREFIX}/include/genericAPI/LDASlogging.i  # [not win]
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: SWIG interface for the LDAS Tools generic library
  - name: python-ldas-tools-ldasgen
    script: install-python.sh
    build:
      activate_in_script: true
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
        - swig
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
        - {{ pin_subpackage('ldas-tools-ldasgen-swig', exact=True) }}
        - python
      run:
        - python
        - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
        - python-ldas-tools-al >={{ ldas_tools_al_version }}
    test:
      imports:
        - LDAStools.LDASlogging
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools generic library

about:
  home: https://wiki.ligo.org/Computing/DASWG/LDASTools
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: SWIG bindings for the LDAS Tools abstraction toolkit

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
