{% set name = "ldas-tools-ldasgen-swig" %}
{% set version = "2.6.9" %}

# dependency versions
{% set ldas_tools_cmake_version = "1.2.3" %}
{% set ldas_tools_al_swig_version = "2.6.9" %}
{% set ldas_tools_ldasgen_version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 6e4edea331f5e257b024de8c82afa52601ff894cee02cdb57bf3b9e361452439

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
    - swig >=3.0.7
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-ldasgen {{ ldas_tools_ldasgen_version }}
  run:
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

test:
  commands:
    - test -f ${PREFIX}/include/genericAPI/LDASlogging.i  # [unix]

outputs:
  - name: ldas-tools-ldasgen-swig

  - name: python-ldas-tools-ldasgen
    script: install-python.sh
    build:
      ignore_run_exports:
        - ldas-tools-ldasgen
      skip: true  # [python_impl != 'cpython']
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.20
        - pkg-config  # [unix]
        - swig >=3.0.7
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - ldas-tools-ldasgen {{ ldas_tools_ldasgen_version }}
        - {{ pin_subpackage('ldas-tools-ldasgen-swig', exact=True) }}
        - python
      run:
        #- ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
        - python
        #- python-ldas-tools-al >={{ ldas_tools_al_swig_version }}
    test:
      imports:
        - LDAStools.LDASlogging
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools.git
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools generic library

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: SWIG interface for the LDAS Tools generic library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
