{% set name = "ldas-tools-ldasgen-swig" %}
{% set version = "2.6.8" %}
{% set sha256 = "1e08bb43cad73d40eb25618e078fa907ec0ed12846d6ff13e54bda6a01e9b0f9" %}

# dependency versions
{% set ldas_tools_cmake_version = "1.0.8" %}
{% set ldas_tools_al_swig_version = "2.6.7" %}
{% set ldas_tools_ldasgen_version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }},<1.2.0
    - ldas-tools-ldasgen {{ ldas_tools_ldasgen_version }}
    - swig >=3.0.7,<4.0.0a0
  run:
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

test:
  commands:
    - test -f ${PREFIX}/include/genericAPI/LDASlogging.i  # [unix]

outputs:
  - name: ldas-tools-ldasgen-swig

  - name: python-ldas-tools-ldasgen
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [unix]
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }},<1.2.0
        - ldas-tools-ldasgen {{ ldas_tools_ldasgen_version }}
        - {{ pin_subpackage('ldas-tools-ldasgen-swig', exact=True) }}
        - python
        - swig >=3.0.7,<4.0.0a0
      run:
        - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
        - python
        - python-ldas-tools-al >={{ ldas_tools_al_swig_version }}
    test:
      imports:
        - LDAStools.LDASlogging
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools generic library

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: SWIG interface for the LDAS Tools generic library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
