# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NowAZQZOsZXGh6deL3wVy+OMGmTtjRYhzmfC4pYZ6NBfTRNzN+hSCejDwv8Ded0JwWkdbMttRRklQL8ZsvYofCY5JXOHq7tBhYVe4t8EM/8Rq/xosQi9Z8eUByOQ7Rt9YHz/ETA2Ti9Jwmn8iFTb2JVyk25bmcIt/vpLqqk1kkXQrS6brjAJlrr3PqwEOipX413ERulteL29Z2OJcOKdULsGVYyBlfhyGyA4+MaCkvWmSheYR6qgbeh+kHXfI1z07Ymxly59KNUAPyaLXO1RsRIfBb3lvDfYTzpDjgOjwJjDRmJpLBfdSQoK8yt2bOYdOLp9ZSF14J+YMs1HT9aF82Elj00yne3ej1YS79USja0WLFOZ28qA/GwK/Vl/NUF6sGDxoTkbnUvc8lpKJ95wZM6V0CHZmeYhpxB6+fGvhwrZf4HaVZsukdMonBzj7tpYoFDRP1iwwXWxddc0s4p33/XO77psUB04+IdygspQjqGfKwa7SJZ9oI499YLM4rt3lp0LuG3ik6Hn8TdSw04wcGNX8Y3mG+5EUH8vXiaiM8LC0E0WJluTaZMBBdOnVHONomp3uuqkyqJ7/eTamXsanGQs+xpORk4pPEb3YD0ZEzMewKhQvsyhmzrNBReIYSRMlbcizoUmy5xb9+5zoyG6QCPUKXQhyFJrrbaw7o7woPg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml