travis:
  secure:
    BINSTAR_TOKEN: NowAZQZOsZXGh6deL3wVy+OMGmTtjRYhzmfC4pYZ6NBfTRNzN+hSCejDwv8Ded0JwWkdbMttRRklQL8ZsvYofCY5JXOHq7tBhYVe4t8EM/8Rq/xosQi9Z8eUByOQ7Rt9YHz/ETA2Ti9Jwmn8iFTb2JVyk25bmcIt/vpLqqk1kkXQrS6brjAJlrr3PqwEOipX413ERulteL29Z2OJcOKdULsGVYyBlfhyGyA4+MaCkvWmSheYR6qgbeh+kHXfI1z07Ymxly59KNUAPyaLXO1RsRIfBb3lvDfYTzpDjgOjwJjDRmJpLBfdSQoK8yt2bOYdOLp9ZSF14J+YMs1HT9aF82Elj00yne3ej1YS79USja0WLFOZ28qA/GwK/Vl/NUF6sGDxoTkbnUvc8lpKJ95wZM6V0CHZmeYhpxB6+fGvhwrZf4HaVZsukdMonBzj7tpYoFDRP1iwwXWxddc0s4p33/XO77psUB04+IdygspQjqGfKwa7SJZ9oI499YLM4rt3lp0LuG3ik6Hn8TdSw04wcGNX8Y3mG+5EUH8vXiaiM8LC0E0WJluTaZMBBdOnVHONomp3uuqkyqJ7/eTamXsanGQs+xpORk4pPEb3YD0ZEzMewKhQvsyhmzrNBReIYSRMlbcizoUmy5xb9+5zoyG6QCPUKXQhyFJrrbaw7o7woPg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
