travis:
  secure:
    BINSTAR_TOKEN: mdPUtOkF8gjZDpsuC+SQC/jLEvwjYoDn1ShDjq4wRqHUHE6un4iiGN7d/UbXgyjYmuheEu03ucOkDhNc+70fHSPl6pGRxDOr2L8TuC3Vkud7QWW3dcGw8yozqg2NwbXIyfKFOYM1DxxzMHjEDqIyiX1vtGogzPs2h9UoV2A112XclTZM77IVRUIwMfsQghCGLjpzX9xZH2YeKyNS3G8LLdSSfpFhMrDBdzCcEQ0rYfXXIgCrZtPXPpJ8qlDTHeXEDgAEkV2nlQs1u3gxQlDpwPDl8qvP6aBLSfGoKsg31KTdW6/GEQ+Qk9xEuyqhctZpm8/jm7Crub8EF60FdDzKsbtnNJ3l8cnj3NwgirjposlPvJwGKYnwXqaqJ9WAw+39AtvSQsVcoMF2yLsHNXBNVSRG5RAwBhLQc1VAp8/YN6ZvfGQ+AeRoqSRh6YCiG78ZEUZBWUVF+ETuu9aCvUIxVZ9RL+Lojr2IXDpEVfwZvYwv+Me+TRsitDd+KFZNjhr86lLiJmO7wNwod74CA8YIvIlF/hJgZiqb7aD2tdmfrLpzIvvb4OJSRwFl223xVJlBubfDc4Rk5nHRhJmArQhKs5+ITlIVN2IvC0Ud+/kaaA/RuYrG7lnCqKqT0x8KVQAIlNeXL/v6H7K5PoOZXewaw5/o3oHLf/ABaiUUUxTflgc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
