travis:
  secure:
    BINSTAR_TOKEN: AuNOAG00nQhJyaailc9ypHVKEBSyDOr0WiP0dsFn1WXl+zs9cQ/+2j5fGJZtyL6Og70cEaGFSZjFHkbdMma2v3IxlRThiHJmP9+2AcsDIC/7rC4/xQjBbl8fco55idoZb6EPF1tbWHehf+3BVyyJMPEZB30anwJeHrjtxTVI6nBpivNh7G6yXqA6xjCd6Cj8VDIPxPD14sgDgfGrGgJtQ+bPBPRW0YCnuT2T0amCHSfrFRp5jpCRYAlKTPz2LQeu8P7CpGcF82wACESdrS8MYtArQEgLmFNQFhU1xyi/KGu6d97KppG1SoINg0Ld9JETB1liycsjZRAyfHXQNZYGvAH9snGcC/+UCMBLu5xaQ3yiQH8Qx2byoingJnnyKKzPfkjx7ErK173FW4pfjhK4lKGSYxYlF/9Apy9cbZxr/7Y1GjyXEwyEc2+t9Ki3A2TXvSJUxub38OipmjsHUNiTGRGIWGsmMMBDAFQ5RqsazUi3NJCl6yWvBGl+61WhruJJKhOmsaWxyj/ns05qZaXz2A/ZGhCqF72SD7Vt+bROTe2Sz+JRo9Z24sqR8rFfryXFV3CgDbgDMtYJNhsUKzlwCXakdQvXCikTUmkx3UEBMycPGIfs50BCrAgDs3I1llmxtOWPmIOmMYEnGK6ON6UudDyIhQTvx1gZfNPnA0CvvGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
